server:
  servlet:
    context-path: /halterocms
spring:
  datasource:
    url:  jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      settings:
        trace: true


#spring.datasource.url=jdbc:h2:file:/data/demo
#SCRIPT NODATA; --> devuelve un ddl de h2

# LAUNCH IN LOCAL
#  spring.datasource.name=yourdbname
#  spring.datasource.initialize=false
#  spring.datasource.url=jdbc:h2:file:~/yourdbname;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=TRUE;DB_CLOSE_DELAY=-1;

#  spring.jpa.hibernate.ddl-auto = update